name: Configuration development module
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_devel.settings

# Information added by Drupal.org packaging script on 2015-10-10
version: '8.x-1.0-beta16+2-dev'
core: '8.x'
project: 'config_devel'
datestamp: 1444445641
